version: '3'

services:

  app1:
    image: nginx
    volumes: ["./app1.txt:/usr/share/nginx/html/app.txt"]

  app2:
    image: nginx
    volumes: ["./app2.txt:/usr/share/nginx/html/app.txt"]

  lb:
    image: nginx
    volumes: ["./default.conf:/etc/nginx/conf.d/default.conf"]
    ports: ["8080:80"]
    depends_on: [app1, app2]

