services:
  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    ports:
      - "8081:8081"
      - "1234:1234"
    environment:
      ENABLE_TELEMETRY: false
    volumes:
      - "cosmos-data:/data"

  cosmos4docker:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    ports:
      - "1235:1235"
    environment:
      ENABLE_TELEMETRY: false
      EXPLORER_PORT: 1235
      # workaround: https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/125
      GATEWAY_PUBLIC_ENDPOINT: "cosmos4docker"
    volumes:
      - "cosmos4docker-data:/data"

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "pass1234"
    ports:
      - "5080:5080"
    volumes:
      - "openobserve-data:/data"

  demo:
    image: demo
    profiles:
      - "demo"
    environment:
      COSMOS_ENDPOINT: "http://cosmos4docker:8081"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: ""

volumes:
  cosmos-data: {}
  cosmos4docker-data: {}
  openobserve-data: {}
