services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "pass1234"
    ports:
      - "5080:5080"
    volumes:
      - data:/data

volumes:
  data: {}
