[tool.poetry]
name = "python-cosmosdb-example"
version = "0.1.0"
description = ""
authors = ["Uragami Taichi <backpaper0@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
azure-cosmos = "^4.7.0"


[tool.poetry.group.dev.dependencies]
taskipy = "^1.12.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start-cosmos = "docker run -d -p 8081:8081 -p 10250-10255:10250-10255 --name cosmos  mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator"
stop-cosmos = "docker stop cosmos"
rm-cosmos = "docker rm cosmos"