version: '3'

services:

  proxy:
    image: nginx
    ports: ["8080:80"]
    volumes: ["./proxy/nginx.conf:/etc/nginx/conf.d/default.conf"]

  api:
    image: openjdk:11
    entrypoint: ["java", "-jar", "/app/api.jar"]
    volumes: ["./api/target/api.jar:/app/api.jar"]

