version: '3'

services:
  reverse-proxy:
    image: nginx
    ports: ["8080:80"]
    volumes: ["./conf.d:/etc/nginx/conf.d"]

  api:
    image: openjdk:11
    entrypoint: ["java", "-jar", "/opt/api/api.jar"]
    volumes: ["./api/target:/opt/api"]
