version: '3.8'

services:

  app1:
    build:
      context: ./app
      dockerfile: Dockerfile

  app2:
    build:
      context: ./app
      dockerfile: Dockerfile

  proxy:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [app1, app2]

