[package]
name = "multiple-binary"
version = "0.1.0"
authors = ["Uragami Taichi <backpaper0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries
[[bin]]
name = "foo"

[[bin]]
name = "bar"

