apiVersion: batch/v1
kind: CronJob
metadata:
  name: date
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: date
              image: busybox
              command:
                - date
          restartPolicy: OnFailure
