version: "3"

services:
  db:
    image: postgres
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
    command: -c log_statement=all

