apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: postgres-operator
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: k8s-postgres-demo:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configtree:/workspace/config/
          volumeMounts:
            - name: datasource-config
              mountPath: /workspace/config
      volumes:
        - name: datasource-config
          secret:
            secretName: hippo-pguser-hippo
            items:
              - key: jdbc-uri
                path: spring/datasource/url
              - key: user
                path: spring/datasource/username
              - key: password
                path: spring/datasource/password
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: postgres-operator
spec:
  selector:
    app: demo
  ports:
    - port: 8080

