apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: postgres-operator
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: k8s-postgres-demo:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: jdbc-uri } }
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: user } }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: password } }
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: postgres-operator
spec:
  selector:
    app: demo
  ports:
    - port: 8080

