version: "2"
services:
    gitbucket:
        image: takezoe/gitbucket
        ports:
            - "8888:8080"
    jenkins:
        image: jenkinsci/jenkins
        ports:
            - "8000:8080"
    tomcat:
        build: tomcat
        ports:
            - "8080:8080"
