//import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function Post() {
    const router = useRouter();
    const id = router.query.id as string;
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {id}
                </h1>

                <p className={styles.description}>
                    <Link href={`/posts?id=${Math.floor(Math.random() * 10000000)}`}>Next</Link>
                </p>

            </main>

        </div>
    )
}
