name: garakuta project CI

on:
  push:
    paths:
      - 'garakuta/**'
      - '.github/workflows/garakuta.yml'

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Test with Maven
        run: mvn test -B

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./garakuta/target/surefire-reports

